directories = [
    "ch0_introduction/00_01_intro",
    "ch0_introduction/00_02_what_you_should_know_text",
    "ch1_setting_up_jenkins/01_01_architect_the_jenkins_environment_on_aws",
    "ch1_setting_up_jenkins/01_02_create_a_security_group",
    "ch1_setting_up_jenkins/01_03_create_a_key_pair",
    "ch1_setting_up_jenkins/01_04_create_the_jenkins_ec2_instance",
    "ch1_setting_up_jenkins/01_05_install_java_jenkins_nginx",
    "ch1_setting_up_jenkins/01_06_configure_nginx",
    "ch1_setting_up_jenkins/01_07_configure_jenkins",
    "ch1_setting_up_jenkins/01_08_challenge_set_up_a_jenkins_master_server",
    "ch1_setting_up_jenkins/01_09_solution_set_up_a_jenkins_master_server",
    "ch2_create_a_build_environment/02_01_plan_the_build_environment",
    "ch2_create_a_build_environment/02_02_create_an_iam_role_for_the_build_server",
    "ch2_create_a_build_environment/02_03_create_a_security_group__key_pair_for_the_build_server",
    "ch2_create_a_build_environment/02_04_create_the_build_server",
    "ch2_create_a_build_environment/02_05_connect_the_jenkins_master_to_the_build_server",
    "ch2_create_a_build_environment/02_06_challenge_set_up_a_build_server",
    "ch2_create_a_build_environment/02_07_solution_set_up_a_build_server",
    "ch3_connect_jenkins_with_webhooks/03_01_plan_the_cicd_pipeline",
    "ch3_connect_jenkins_with_webhooks/03_02_whats_a_webhook",
    "ch3_connect_jenkins_with_webhooks/03_03_create__test_a_webhook_with_github",
    "ch3_connect_jenkins_with_webhooks/03_04_create__test_a_webhook_with_gitlab_text",
    "ch3_connect_jenkins_with_webhooks/03_05_create__test_a_webhook_with_bitbucket_text",
    "ch3_connect_jenkins_with_webhooks/03_06_challenge_connect_jenkins_to_github",
    "ch3_connect_jenkins_with_webhooks/03_07_solution_connect_jenkins_to_github",
    "ch4_deploy_code_to_aws_lambda/04_01_plan_the_deployment_target_in_aws_lambda",
    "ch4_deploy_code_to_aws_lambda/04_02_create_lambda_functions",
    "ch4_deploy_code_to_aws_lambda/04_03_create_a_github_repository_for_the_application_code",
    "ch4_deploy_code_to_aws_lambda/04_04_create_a_freestyle_job_to_deploy_code_from_github_part_1",
    "ch4_deploy_code_to_aws_lambda/04_05_create_a_freestyle_job_to_deploy_code_from_github_part_2",
    "ch4_deploy_code_to_aws_lambda/04_06_deploy_to_aws_lambda_from_github",
    "ch4_deploy_code_to_aws_lambda/04_07_challenge_deploy_to_aws_lambda_from_github",
    "ch4_deploy_code_to_aws_lambda/04_08_solution_deploy_to_aws_lambda_from_github",
    "ch5_shut_down_aws_resources/05_01_stop_or_remove_aws_resources",
    "ch5_shut_down_aws_resources/05_02_challenge_decommission_your_jenkins_servers",
    "ch5_shut_down_aws_resources/05_03_solution_decommission_your_jenkins_servers",
    "ch6_conclusion/06_01_next_steps"
]

titles = [
    "# 0_01 Intro",
    "# 0_02 What you should know (TEXT)",
    "# 01_01 Architect the Jenkins Environment on AWS",
    "# 01_02 Create a security group",
    "# 01_03 Create a key pair",
    "# 01_04 Create the Jenkins EC2 instance",
    "# 01_05 Install Java, Jenkins, NGINX",
    "# 01_06 Configure NGINX",
    "# 01_07 Configure Jenkins",
    "# 01_08 Challenge Set up a Jenkins master server",
    "# 01_09 Solution Set up a Jenkins master server",
    "# 02_01 Plan the build environment",
    "# 02_02 Create an IAM role for the build server",
    "# 02_03 Create a security group and key pair for the build server",
    "# 02_04 Create the build server",
    "# 02_05 Connect the Jenkins master to the build server",
    "# 02_06 Challenge Set up a build server",
    "# 02_07 Solution Set up a build server",
    "# 03_01 Plan the CI/CD pipeline",
    "# 03_02 What's a webhook?",
    "# 03_03 Create and test a webhook with GitHub",
    "# 03_04 Create and test a webhook with GitLab (TEXT)",
    "# 03_05 Create and test a webhook with Bitbucket (TEXT)",
    "# 03_06 Challenge Connect Jenkins to GitHub",
    "# 03_07 Solution Connect Jenkins to GitHub",
    "# 04_01 Plan the Deployment Target in AWS Lambda",
    "# 04_02 Create Lambda Functions",
    "# 04_03 Create a GitHub repository for the application code",
    "# 04_04 Create a freestyle job to deploy code from GitHub, part 1",
    "# 04_05 Create a freestyle job to deploy code from GitHub, part 2",
    "# 04_06 Deploy to AWS Lambda from GitHub",
    "# 04_07 Challenge Deploy to AWS Lambda from GitHub",
    "# 04_08 Solution Deploy to AWS Lambda from GitHub",
    "# 05_01 Stop or remove AWS resources",
    "# 05_02 Challenge Decommission your Jenkins servers",
    "# 05_03 Solution Decommission your Jenkins servers",
    "# 06_01 Next Steps"
]

for index, directory in enumerate(directories):
    with open(f"{directory}/README.md", "r") as file:
        content = file.read()
    with open(f"{directory}/README.md", "w") as file:
        file.write(content + titles[index] + "\n<!-- FooterStart -->\n<!-- FooterEnd -->\n")
